### ISSUE TITLE
Hide Mesh Light for render

### ISSUE THREAD

**Issue by JuhaW** [TheBounty/Core#13]
Option to hide Mesh Light for render, just like Portal light.

**Comment by povmaniaco** [comment]
Very easy to implementing.. but in the exporter side. Its ready for a new release :)
[commit](https://github.com/TheBounty/Blender-Exporter/commit/2a6d5c77ccaa90d92cf8e62f14062813ab9e830f)

**Comment by povmaniaco** [comment]
Done The code are pushed to repo: [mesh light changes](https://github.com/TheBounty/Blender-Exporter/commit/97a224efdd33ce6fb58fe23b5ea647b8902001f6)
Closed.
