### ISSUE TITLE
outputFilename had already been implemented

### ISSUE THREAD

**Issue by rubdos** [TheBounty/Core#14]
I just noticed something VERY stupid I did... Remeber I added the -o option?
It had already been done and none of us has seen. Please revert my patch.

`Usage: yafaray-xml [OPTIONS]... <input xml file> [output filename]`

you see, there's an optional argument [output filename]. I don't know why I added my code. Very stupid :)

The current/original implementation could use some cleaning though, I think:
```
	if(files.size() > 1) outName = files[1] + "." + format;
```

**Comment by povmaniaco** [comment]
This isue is fixed.
