### ISSUE TITLE
Bump map on glossy material

### ISSUE THREAD

**Issue by rubdos** [TheBounty/Core#18]
According to [this forum post by jzs](https://www.thebountyrenderer.org/node/146), bump map on glossy material doesn't work. Blender is working atm, so can't test. Can anyone confirm?

**Comment by povmaniaco** [comment]
This issue is solved in this commit: https://github.com/TheBounty/Blender-Exporter/commit/76726baed13f448417e92dcdd1c06098794fc5f4
The 'jzs' user report issue is remain on last build from thebountyrenderer site, but solved on the current 0.1.6.rc3 branch

**Comment by rubdos** [comment]
Roger that. Issue can be closed then.
